name: build-mod
on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:

permissions: read-all

jobs:
  build-the-mod:
    permissions:
      contents: write
      actions: read
    uses: argonui/TTSModManager.action/action.yml@v0.1.0

